In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("addition:",arr1+arr2)
print("subtraction:",arr2-arr1)

addition: [11 22 33 44 55]
subtraction: [ 9 18 27 36 45]


In [14]:
arr1=np.array([2,3,4,5,6])
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array:\n",arr)

array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])